"use client";

import Link from "next/link";
import {
  FaArrowLeft,
  FaDownload,
  FaFileAlt,
  FaMoneyBillWave,
  FaUsers,
  FaBed,
  FaTools,
} from "react-icons/fa";

type ReportDetailsProps = {
  reportId: string;
};

const reportData: Record<
  string,
  {
    name: string;
    type: string;
    period: string;
    generated: string;
    description: string;
  }
> = {
  "RPT-001": {
    name: "September Occupancy Report",
    type: "Occupancy",
    period: "September 2026",
    generated: "Sep 20, 2026",
    description: "Summary of hostel room and bed occupancy for the selected period.",
  },
  "RPT-002": {
    name: "September Financial Report",
    type: "Financial",
    period: "September 2026",
    generated: "Sep 20, 2026",
    description: "Summary of payments and financial activity for the selected period.",
  },
  "RPT-003": {
    name: "Resident Summary Report",
    type: "Residents",
    period: "September 2026",
    generated: "Sep 19, 2026",
    description: "Summary of registered and active residents.",
  },
  "RPT-004": {
    name: "Complaints & Maintenance Report",
    type: "Complaints",
    period: "September 2026",
    generated: "Sep 18, 2026",
    description: "Summary of complaints and maintenance issues reported by residents.",
  },
};

function typeStyles(type: string) {
  switch (type) {
    case "Occupancy":
      return "bg-blue-50 text-blue-700";
    case "Financial":
      return "bg-green-50 text-green-700";
    case "Residents":
      return "bg-purple-50 text-purple-700";
    case "Complaints":
      return "bg-yellow-50 text-yellow-700";
    default:
      return "bg-gray-100 text-gray-600";
  }
}

export default function ReportDetails({
  reportId,
}: ReportDetailsProps) {
  const report = reportData[reportId] ?? reportData["RPT-001"];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <Link
            href="/admin/reports"
            className="flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50"
          >
            <FaArrowLeft size={14} />
          </Link>

          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {report.name}
            </h1>

            <p className="mt-1 text-sm text-gray-500">
              Report ID: {reportId}
            </p>
          </div>
        </div>

        <button
          type="button"
          className="flex items-center justify-center gap-2 rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-teal-700"
        >
          <FaDownload size={14} />
          Export Report
        </button>
      </div>

      {/* Report Information */}
      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
        <div className="flex items-start gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-teal-50 text-teal-600">
            <FaFileAlt size={20} />
          </div>

          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="font-semibold text-gray-900">
                {report.name}
              </h2>

              <span
                className={`rounded-full px-3 py-1 text-xs font-medium ${typeStyles(
                  report.type
                )}`}
              >
                {report.type}
              </span>
            </div>

            <p className="mt-2 text-sm text-gray-500">
              {report.description}
            </p>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-1 gap-4 border-t border-gray-100 pt-5 sm:grid-cols-3">
          <div>
            <p className="text-xs text-gray-500">Report Period</p>
            <p className="mt-1 text-sm font-medium text-gray-900">
              {report.period}
            </p>
          </div>

          <div>
            <p className="text-xs text-gray-500">Generated</p>
            <p className="mt-1 text-sm font-medium text-gray-900">
              {report.generated}
            </p>
          </div>

          <div>
            <p className="text-xs text-gray-500">Generated By</p>
            <p className="mt-1 text-sm font-medium text-gray-900">
              Admin
            </p>
          </div>
        </div>
      </div>

      {/* Summary */}
      <div>
        <h2 className="mb-4 text-lg font-semibold text-gray-900">
          Report Summary
        </h2>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <SummaryCard
            title="Occupancy"
            value="82%"
            description="41 / 50 beds"
            icon={FaBed}
          />

          <SummaryCard
            title="Payments"
            value="GH₵48,500"
            description="Confirmed this month"
            icon={FaMoneyBillWave}
          />

          <SummaryCard
            title="Residents"
            value="41"
            description="Active residents"
            icon={FaUsers}
          />

          <SummaryCard
            title="Open Issues"
            value="7"
            description="Pending & in progress"
            icon={FaTools}
          />
        </div>
      </div>

      {/* Report Content */}
      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
        <h2 className="font-semibold text-gray-900">
          Report Details
        </h2>

        <div className="mt-5 overflow-x-auto">
          <table className="w-full min-w-[600px] text-left">
            <thead className="border-b border-gray-200 bg-gray-50">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold uppercase text-gray-500">
                  Metric
                </th>

                <th className="px-4 py-3 text-xs font-semibold uppercase text-gray-500">
                  Value
                </th>

                <th className="px-4 py-3 text-xs font-semibold uppercase text-gray-500">
                  Status
                </th>
              </tr>
            </thead>

            <tbody className="divide-y divide-gray-100">
              <ReportRow
                metric="Total Beds"
                value="50"
                status="Available"
              />

              <ReportRow
                metric="Occupied Beds"
                value="41"
                status="Active"
              />

              <ReportRow
                metric="Available Beds"
                value="9"
                status="Available"
              />

              <ReportRow
                metric="Confirmed Payments"
                value="GH₵48,500"
                status="Confirmed"
              />
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function SummaryCard({
  title,
  value,
  description,
  icon: Icon,
}: {
  title: string;
  value: string;
  description: string;
  icon: React.ElementType;
}) {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-500">{title}</p>

        <Icon className="text-teal-600" size={18} />
      </div>

      <h3 className="mt-3 text-2xl font-bold text-gray-900">
        {value}
      </h3>

      <p className="mt-1 text-xs text-gray-500">
        {description}
      </p>
    </div>
  );
}

function ReportRow({
  metric,
  value,
  status,
}: {
  metric: string;
  value: string;
  status: string;
}) {
  return (
    <tr>
      <td className="px-4 py-4 text-sm font-medium text-gray-900">
        {metric}
      </td>

      <td className="px-4 py-4 text-sm text-gray-600">
        {value}
      </td>

      <td className="px-4 py-4">
        <span className="rounded-full bg-green-50 px-3 py-1 text-xs font-medium text-green-700">
          {status}
        </span>
      </td>
    </tr>
  );
}